---

- name: Download Helm installation script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'

- name: Run Helm installation script
  command: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm
  register: helm_install_result
  changed_when: false

- name: Add /usr/local/bin to PATH
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:/usr/local/bin'
  when: helm_install_result.rc == 0

- name: Ensure bash-completion package is installed
  package:
    name: bash-completion
    state: present

- name: Add Helm completion to .bashrc
  lineinfile:
    path: "~/.bashrc"
    line: 'source <(helm completion bash)'
    create: yes
    state: present

- name: Apply changes to the current shell
  shell: "source ~/.bashrc"
  args:
    executable: /bin/bash
