---
- name: Create nfs namespace for nfs-storageClass 
  shell: kubectl create namespace nfs
  ignore_errors: yes

- name: Add  repository
  shell: helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  ignore_errors: yes 

- name: Update repository using Helm
  shell: helm repo update
  ignore_errors: yes

- name: Deploy nfs-storageClass using Helm
  shell: helm install nfs nfs-subdir-external-provisioner/nfs-subdir-external-provisioner --set nfs.server={{  nfs_server_endpoint  }} --set nfs.path={{  nfs_data_Path  }} --set storageClass.onDelete=true -n nfs
  ignore_errors: yes

- name: Pause for 1 minute to allow prometheus and ghafana to initialize
  pause:
    minutes: 1 
