---
- name: Create argocd namespace
  shell: kubectl create namespace argocd
  ignore_errors: yes

- name: Add Argo CD repository
  shell: helm repo add argo https://argoproj.github.io/argo-helm
  ignore_errors: yes

- name: Update repository using Helm
  shell: helm repo update
  ignore_errors: yes

- name: Install Argo CD using Helm
  shell: helm install -n argocd argocd argo/argo-cd
  ignore_errors: yes

- name: Pause for 1 minute to allow Argo CD to initialize
  pause:
    minutes: 2

- name: Get argocd-svc service
  shell: kubectl -n argocd get service argocd-server -o yaml > /tmp/argocd-svc.yml
  ignore_errors: yes

- name: Update argocd-svc file
  replace:
    path: /tmp/argocd-svc.yml
    regexp: 'ClusterIP'
    replace: 'NodePort'
  ignore_errors: yes

- name: Apply the modified argocd-svc service
  shell: kubectl apply -f /tmp/argocd-svc.yml
  ignore_errors: yes  

##kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d ; echo
  
